--INSERT INTO "kesplus_app"."kes_ldap" ("id", "urls", "user_dn", "base", "password", "create_time", "create_by","enabled")
--VALUES(lower(sys_guid()), 'ldap://10.12.13.251:389', 'cn=admin,dc=zaq,dc=test', 'dc=zaq,dc=test', 'XXX', sysdate, null,0);
