INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('7', 7, 1, '0', '数据服务', 'datas', NULL, 1, 4, NULL, NULL, '/sys/app/directory', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('3', 3, 1, '0', '函数', 'functions', NULL, 1, 0, NULL, NULL, '/sys/func/list', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('4', 4, 1, '0', '存储过程', 'procedures', NULL, 1, 0, NULL, NULL, '/sys/func/list', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('2', 2, 1, '0', '视图', 'views', NULL, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('6', 6, 1, '0', '定时任务', 'jobs', NULL, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('5', 5, 1, '0', '包', 'packages', NULL, 1, 0, NULL, NULL, '/sys/pkg/list', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('13', 8, 1, '0', '菜单定义', 'menus', NULL, 1, 0, NULL, NULL, '/kes/menus/children', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('19', 2, 3, '12', '单元测试', 'cases', NULL, 1, 0, NULL, NULL, '/sys/autotest/case/tree', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('20', 3, 3, '12', '组合测试', 'scenes', NULL, 1, 0, NULL, NULL, '/sys/autotest/tree', NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES ('1', 1, 1, '0', '表', 'tables', NULL, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO "kesplus_app"."kes_app_directory" ("id", "sort_num", "directory_type", "pid", "directory_name", "directory_code", "directory_icon", "status", "sub_count", "app_id", "create_time", "child_api", "tenant_id") VALUES('21', 1, 3, '12', '全局参数', 'params', NULL, 1, 0, NULL, NULL, NULL, NULL);


INSERT INTO kesplus_app.kes_app_directory ("id","sort_num","directory_type","pid","directory_name","directory_code","directory_icon","status","sub_count","app_id","create_time","child_api","tenant_id") VALUES
          ('9',1,2,'7','RESTful','restful',NULL,1,0,NULL,NULL,'/sys/restful/list',NULL),
          ('10',2,2,'7','数据权限','policys',NULL,1,0,'1',NULL,'/kes/policy/ctree',NULL),
          ('14',3,2,'7','权限点定义','permissions',NULL,1,0,'1',NULL,'/kes/kesPermission/listByPid',NULL),
          ('11',4,2,'7','内置角色定义','roles',NULL,1,0,NULL,NULL,'/kes/roles/list',NULL),
          ('12',5,2,'7','自动化测试','tests',NULL,1,2,NULL,NULL,'/sys/app/directory',NULL) ;
