INSERT INTO "kesplus_app"."kes_app_formdesign_custom"
("id", "group", "block_title", "block_icon", "status", "widget_json", "create_time", "create_by", "update_time", "update_by", "tenant_id")
VALUES('5f719036b0f84cac89134d9d4ce67c7a', 'layout', '上下布局1', 'Baseball', 0, '{"key":23437,"type":"layout1","subCategory":"layout","category":"container","icon":"sub-form","widgetList":[],"widgetList_top":[{"type":"layout-sub","category":"container","icon":"sub-form","internal":true,"widgetList":[],"title":"header","options":{"name":"layout-sub","label":"layout-sub","hidden":false,"hiddenExpression":"","active":false,"disabled":false,"disabledExpression":"","customClass":"","backgroundColor":""},"id":"layout-sub-91392"}],"widgetList_bottom":[{"type":"layout-sub","category":"container","icon":"sub-form","internal":true,"widgetList":[{"key":29691,"type":"radio","icon":"radio-field","formItemFlag":true,"options":{"stageButton":"","blockObj":{"group":"","blockTitle":"","blockIcon":""},"name":"radio39997","label":"radio","labelAlign":"","defaultValue":null,"columnWidth":"200px","size":"","displayStyle":"inline","buttonStyle":false,"border":false,"labelWidth":null,"labelHidden":false,"disabled":false,"disabledExpression":"","hidden":false,"hiddenExpression":"","optionItems":[{"label":"radio 1","value":1},{"label":"radio 2","value":2},{"label":"radio 3","value":3}],"required":false,"requiredHint":"","validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"radio39997"}],"title":"main","options":{"name":"layout-sub","label":"layout-sub","hidden":false,"hiddenExpression":"","active":false,"disabled":false,"disabledExpression":"","customClass":[],"backgroundColor":""},"id":"layout-sub-52298"}],"widgetList_left":[],"widgetList_right":[],"widgetList_center":[],"options":{"name":"layout129373","hidden":false,"hiddenExpression":"","customClass":[],"stageButton":"","blockObj":{"group":"layout","blockTitle":"上下布局1","blockIcon":"Baseball"}},"id":"layout129373","group":"layout","blockTitle":"上下布局1","blockIcon":"Baseball"}', '2022-09-28 09:27:03', NULL, NULL, NULL, NULL);
INSERT INTO "kesplus_app"."kes_app_formdesign_custom"
("id", "group", "block_title", "block_icon", "status", "widget_json", "create_time", "create_by", "update_time", "update_by", "tenant_id")
VALUES('2340b8dde35143609525116abe6ec70b', '表单', '测试表单', NULL, 0, '{
    "key": 82368,
    "type": "input",
    "icon": "text-field",
    "formItemFlag": true,
    "options": {
        "stageButton": "",
        "blockObj": {
            "blockTitle": "",
            "blockIcon": ""
        },
        "name": "input85623",
        "label": "input",
        "labelAlign": "",
        "type": "text",
        "defaultValue": "",
        "placeholder": "",
        "columnWidth": "",
        "size": "",
        "labelWidth": null,
        "labelHidden": false,
        "readonly": false,
        "disabled": false,
        "disabledExpression": "",
        "hidden": false,
        "hiddenExpression": "",
        "clearable": true,
        "showPassword": false,
        "required": false,
        "requiredHint": "",
        "validation": "",
        "validationHint": "",
        "customClass": "",
        "labelIconClass": null,
        "labelIconPosition": "rear",
        "labelTooltip": null,
        "minLength": null,
        "maxLength": null,
        "showWordLimit": false,
        "prefixIcon": "",
        "suffixIcon": "",
        "appendButton": false,
        "appendButtonDisabled": false,
        "buttonIcon": "custom-search",
        "onCreated": "",
        "onMounted": "",
        "onInput": "",
        "onChange": "",
        "onFocus": "",
        "onBlur": "",
        "onValidate": ""
    },
    "id": "input85623"
}', '2022-10-08 13:29:32', NULL, NULL, NULL, NULL);
INSERT INTO "kesplus_app"."kes_app_formdesign_custom"
("id", "group", "block_title", "block_icon", "status", "widget_json", "create_time", "create_by", "update_time", "update_by", "tenant_id")
VALUES('e1c9e183fe1847ec8e142a3d25b20021', '表单', '测试表单', NULL, 0, '{
    "key": 82368,
    "type": "input",
    "icon": "text-field",
    "formItemFlag": true,
    "options": {
        "stageButton": "",
        "blockObj": {
            "blockTitle": "",
            "blockIcon": ""
        },
        "name": "input85623",
        "label": "input",
        "labelAlign": "",
        "type": "text",
        "defaultValue": "",
        "placeholder": "",
        "columnWidth": "",
        "size": "",
        "labelWidth": null,
        "labelHidden": false,
        "readonly": false,
        "disabled": false,
        "disabledExpression": "",
        "hidden": false,
        "hiddenExpression": "",
        "clearable": true,
        "showPassword": false,
        "required": false,
        "requiredHint": "",
        "validation": "",
        "validationHint": "",
        "customClass": "",
        "labelIconClass": null,
        "labelIconPosition": "rear",
        "labelTooltip": null,
        "minLength": null,
        "maxLength": null,
        "showWordLimit": false,
        "prefixIcon": "",
        "suffixIcon": "",
        "appendButton": false,
        "appendButtonDisabled": false,
        "buttonIcon": "custom-search",
        "onCreated": "",
        "onMounted": "",
        "onInput": "",
        "onChange": "",
        "onFocus": "",
        "onBlur": "",
        "onValidate": ""
    },
    "id": "input85623"
}', '2022-10-08 17:46:58', NULL, NULL, NULL, NULL);
