CREATE OR REPLACE FUNCTION public.fun_check_jdbc_role(role_name varchar DEFAULT NULL::varchar)
 RETURNS boolean
AS WRAPPED
MpqEPqA8z85benlzsfkPmFPP+h3SnZD1conFwi3xCQEXH/IXbpT6lweXGgWP
fUHQsB7nbFgN1YThstupGDFjz+eCyy+9dlJp+q6GacKlhxJr4c35Yo0YrdiH
3a1paMrVHtye8Yz8MgaHP+DCL18q+k1xlIgw2qsVL3Hr8wL712dZrxZfQQPp
tenVPGARyvx3YMffL1AQ5MTY5Q1pTU2WVd2u/Vlh1Tlf4QBigc9VtjGWyTKx
5XztcvLPpghhFCGc
END;

