CREATE OR REPLACE PACKAGE "public"."cache" AUTHID CURRENT_USER AS
	_CONTEXT JSONB := '{}'::jsonb;
	_KEY_TOKEN CONSTANT TEXT := 'TOKEN';
	_KEY_USER CONSTANT TEXT := 'USER';
	_KEY_RESTFUL CONSTANT TEXT := 'RESTFUL';
	_KEY_REQUEST CONSTANT TEXT := 'REQUEST';
	_KEY_SETTING CONSTANT TEXT := 'SETTING';
	_KEY_EX_STACK CONSTANT TEXT := 'EX_STACK';
	_KEY_SESSION CONSTANT TEXT := 'SESSION';
END;

CREATE OR REPLACE PACKAGE BODY "public"."cache" AS WRAPPED
I/HnejJ4IvYHChEGp8PloA==
END;

