CREATE OR REPLACE PACKAGE "public"."error_code" AUTHID CURRENT_USER AS
    SUCCESS CONSTANT TEXT := '200'; 
	FAIL CONSTANT TEXT := '500'; 
    DATA_NO_FOUND CONSTANT TEXT := '404';  
    
    VARIABLE_CANNOT_EMPTY CONSTANT TEXT := 'session_variable_1001';  
end;

CREATE OR REPLACE PACKAGE BODY "public"."error_code" AS WRAPPED
I/HnejJ4IvYHChEGp8PloA==
END;

