CREATE OR REPLACE PACKAGE "kesplus_app"."error_code" AUTHID CURRENT_USER AS
    
    SUCCESS CONSTANT TEXT := '200';
    
    FAIL CONSTANT TEXT := '500';
    
    DATA_NO_FOUND CONSTANT TEXT := '404';
    
    KESPLUS_SQL_EDIT_NO_CORRESPONDING_NODE_CODE_1001 CONSTANT TEXT := 'kesplus_sqledit_1001';
    
    KESPLUS_SQL_EDIT_OBJECT_IS_LOCKED_1002 CONSTANT TEXT := 'kesplus_sqledit_1002';
    
    KESPLUS_REST_API_NOT_EXIST_1001 CONSTANT TEXT := 'kesplus_rest_1001';
    
    KESPLUS_REST_API_VERSION_ALREADY_EXIST_1002 CONSTANT TEXT := 'kesplus_rest_1002';
    
    KESPLUS_FORMDATA_SAVE_CAN_NOT_BE_EMPTY_1001 CONSTANT TEXT := 'kesplus_formdata_1001';
    
    KESPLUS_FORMDATA_DELETE_CAN_NOT_BE_EMPTY_1002 CONSTANT TEXT := 'kesplus_formdata_1002';
    
    KESPLUS_FORMDATA_UPDATE_CAN_NOT_BE_EMPTY_1003 CONSTANT TEXT := 'kesplus_formdata_1003';
    
    KESPLUS_FORMDATA_NAME_ALREADY_EXISTS_1004 CONSTANT TEXT := 'kesplus_formdata_1004';
    
    KESPLUS_FORMDATA_NAME_CAN_NOT_BE_EMPTY_1005 CONSTANT TEXT := 'kesplus_formdata_1005';
    
    KESPLUS_FORMDATA_CAN_NOT_BE_EMPTY_1006 CONSTANT TEXT := 'kesplus_formdata_1006';
    
    KESPLUS_GET_OBJECT_ID_CAN_NOT_BE_EMPTY_1001 CONSTANT TEXT := 'kesplus_appbuild_1001';
    
    KESPLUS_TEMPLATE_SELECT_TEMPLATE_1001 CONSTANT TEXT := 'kesplus_template_1001';
    
    KESPLUS_TEMPLATE_DATA_NOT_FOUND_1002 CONSTANT TEXT := 'kesplus_template_1002';
    
    KESPLUS_DOCUMENT_TYPE_VALIDATE_FAIL CONSTANT TEXT := 'kesplus_document_1001';
    
    KESPLUS_FILE_FILETYPE_CAN_NOT_BE_EMPTY_1001 CONSTANT TEXT := 'kesplus_file_1001';
    
    KESPLUS_FILE_FILESUFFIX_CAN_NOT_BE_EMPTY_1002 CONSTANT TEXT := 'kesplus_file_1002';
    
    KESPLUS_FILE_FILEPATH_CAN_NOT_BE_EMPTY_1003 CONSTANT TEXT := 'kesplus_file_1003';
    
    KESPLUS_ROLE_ROLENAME_ROLEDIR_CANNOT_BE_SAME_1001 CONSTANT TEXT := 'kesplus_role_1001';
    
    KESPLUS_ROLE_UPPER_LEVEL_MUSTBE_DIR_1002 CONSTANT TEXT := 'kesplus_role_1002';
    
    KESPLUS_ROLE_NAME_ALREADY_EXISTS_1003 CONSTANT TEXT := 'kesplus_role_1003';
    
    KESPLUS_ROLE_ALREADY_EXISTS_1004 CONSTANT TEXT := 'kesplus_role_1004';
    
    KESPLUS_ROLE_CANNOT_MANIPULATE_BUILTIN_ROLES_1005 CONSTANT TEXT := 'kesplus_role_1005';
    
    KESPLUS_ROLE_CANNOT_AUTHORIZE_DIRECTORY_1006 CONSTANT TEXT := 'kesplus_role_1006';
    
    KESPLUS_ROLE_HAS_BEEN_ASSOCIATED_1007 CONSTANT TEXT := 'kesplus_role_1007';
    
    KESPLUS_ROLE_DOES_NOT_EXIST_1008 CONSTANT TEXT := 'kesplus_role_1008';
    
    KESPLUS_ROLE_DELETE_CHILD_FIRST_1009 CONSTANT TEXT := 'kesplus_role_1009';
    
    KESPLUS_POLICY_NO_SELECT_BUSINESS_TABLE_1001 CONSTANT TEXT := 'kesplus_policy_1001';
    
    KESPLUS_POLICY_UPPER_LEVEL_MUSTBE_DIR_1002 CONSTANT TEXT := 'kesplus_policy_1002';
    
    KESPLUS_POLICY_NOT_ALLOWED_CROSS_MODULE_MOVE_1003 CONSTANT TEXT := 'kesplus_policy_1003';
    
    KESPLUS_POLICY_CANNOT_DELETE_ASSOCIATED_ROLE_1004 CONSTANT TEXT := 'kesplus_policy_1004';
    
    KESPLUS_POLICY_MISSING_PARAMTERS_1005 CONSTANT TEXT := 'kesplus_policy_1005';
    
    KESPLUS_POLICY_MISSING_MODULE_PARAMTERS_1006 CONSTANT TEXT := 'kesplus_policy_1006';
    
    KESPLUS_POLICY_PERMISSION_STATUS_INCORRECT_1007 CONSTANT TEXT := 'kesplus_policy_1007';
    
    KESPLUS_MENU_CODE_ALREADY_EXISTS_1001 CONSTANT TEXT := 'kesplus_menu_1021';
    
    KESPLUS_MENU_UPPER_LEVEL_MUSTBE_DIR_1002 CONSTANT TEXT := 'kesplus_menu_1002';
    
    KESPLUS_MENU_REPEATS_AT_CURRENT_LEVEL_1003 CONSTANT TEXT := 'kesplus_menu_1003';
    
    KESPLUS_MENU_DELETE_SUBORDINATE_PERMISSION_FIRST_1004 CONSTANT TEXT := 'kesplus_menu_1004';
    
    KESPLUS_MENU_DIRECTORY_CANNOT_CHANGE_TO_NON_DIRECTORY_1005 CONSTANT TEXT := 'kesplus_menu_1005';
    
    KESPLUS_FILTER_FILTERCODE_CAN_NOT_BE_EMPTY_1001 CONSTANT TEXT := 'kesplus_filter_1001';
    
    KESPLUS_FILTER_FILTERNAME_CAN_NOT_BE_EMPTY_1002 CONSTANT TEXT := 'kesplus_filter_1002';
    
    KESPLUS_FILTER_ORDERRANGE_1003 CONSTANT TEXT := 'kesplus_filter_1003';
    
    KESPLUS_FILTER_FILTERID_CAN_NOT_BE_EMPTY_1004 CONSTANT TEXT := 'kesplus_filter_1004';
     
    KESPLUS_FILTER_SYSTEMFILTER_CAN_NOT_BE_EDIT_1005 CONSTANT TEXT := 'kesplus_filter_1005';
        
    KESPLUS_FILTER_FILTER_CAN_NOT_BE_EXSIST_1006 CONSTANT TEXT := 'kesplus_filter_1006';
        
    KESPLUS_FILTER_FILTER_CAN_NOT_BE_DROP_1007 CONSTANT TEXT := 'kesplus_filter_1007';
       
    KESPLUS_FILTER_ERROR_VERSION_CODE_1008 CONSTANT TEXT := 'kesplus_filter_1008';
     
    KESPLUS_FORM_FORMNAME_CAN_NOT_BE_EMPTY_1001 CONSTANT TEXT := 'kesplus_form_1001';
     
    KESPLUS_FORM_FORMCODE_CAN_NOT_BE_EMPTY_1002 CONSTANT TEXT := 'kesplus_form_1002';
    
    KESPLUS_FORM_CODEEXISTS_1003 CONSTANT TEXT := 'kesplus_form_1003';
    
    KESPLUS_FORM_MODULEID_CAN_NOT_BE_EMPTY_1004 CONSTANT TEXT := 'kesplus_form_1004';
     
    KESPLUS_FORM_FROMID_CAN_NOT_BE_EMPTY_1005 CONSTANT TEXT := 'kesplus_form_1005';
     
    KESPLUS_FORM_BOUNDPROCESS_1006 CONSTANT TEXT := 'kesplus_form_1006';
      
    KESPLUS_FORM_FORMMODEL_NOTEXISTS_1007 CONSTANT TEXT := 'kesplus_form_1007';
      
    KESPLUS_FORM_CONFIGUREMODEL_TABLE_INFORMATION_1008 CONSTANT TEXT := 'kesplus_form_1008';
     
    KESPLUS_FORM_SET_FOREIGNKEY_1009 CONSTANT TEXT := 'kesplus_form_1009';
      
    KESPLUS_FORM_CONFIGURE_FORM_PROPERTIES_1010 CONSTANT TEXT := 'kesplus_form_1010';
       
    KESPLUS_FORM_CONFIGURE_LIST_PROPERTIES_1011 CONSTANT TEXT := 'kesplus_form_1011';
         
    KESPLUS_FORM_INPUT_MODULEID_1012 CONSTANT TEXT := 'kesplus_form_1012';
         
    KESPLUS_FORM_INPUT_TABLENAME_1013 CONSTANT TEXT := 'kesplus_form_1013';
       
    KESPLUS_FORMBIND_PROCESSID_1001 CONSTANT TEXT := 'kesplus_formbind_1001';
       
    KESPLUS_FORMBIND_INPUT_FORMCODE_1002 CONSTANT TEXT := 'kesplus_formbind_1002';
         
    KESPLUS_FORMBIND_IDNOT_EXISTS_1003 CONSTANT TEXT := 'kesplus_formbind_1003';
       
    KESPLUS_FORMBIND_DISPOSITON_ID_NOT_EMPTY_1004 CONSTANT TEXT := 'kesplus_formbind_1004';
          
    KESPLUS_FORMBIND_NODE_ID_NOT_EMPTY_1005 CONSTANT TEXT := 'kesplus_formbind_1005';
       
    KESPLUS_FORMBOIND_DISPOSITION_NOT_EXISTS_1006 TEXT := 'kesplus_formbind_1006';
     
    KESPLUS_FORMGENERATOR_FROM_TYPE_UNKNOWN_1001 CONSTANT TEXT := 'kesplus_formgenerator_1001';
          
    KESPLUS_FORMGENERATOR_DISPOSITION_INFO_1002 CONSTANT TEXT := 'kesplus_formgenerator_1002';
    
    KESPLUS_FUNCTION_INPUT_NEW_NAME_1001 CONSTANT TEXT := 'kesplus_functions_1001';
     
    KESPLUS_FUNCTION_ALREADY_EXISTS_1002 CONSTANT TEXT := 'kesplus_functions_1002';
    
    KESPLUS_FUNCTION_Procedures_ALREADY_EXISTS_1003 CONSTANT TEXT := 'kesplus_functions_1003';
     
    KESPLUS_FUNCTION_PARA_IS_INVALID_1004 CONSTANT TEXT := 'kesplus_functions_1004';
    
    KESPLUS_INIT_MODULE_PARA_NOT_EMPTY_1001 CONSTANT TEXT := 'kesplus_init_1001';
          
    KESPLUS_INIT_BUS_PARA_NOT_EMPTY_1002 CONSTANT TEXT := 'kesplus_init_1002';
    
    KESPLUS_INIT_GENERATE_CODE_1003 CONSTANT TEXT := 'kesplus_init_1003';
    
    KESPLUS_JOBS_TASK_NOT_EXISTS_1001 CONSTANT TEXT := 'kesplus_jobs_1001';
     
    KESPLUS_JOBS_DIRETORY_NOT_EXISTS_1002 CONSTANT TEXT := 'kesplus_jobs_1002';
    
    KESPLUS_JOBS_SCHEDULED_TASK_DIRECTORY_REPEAT_1003 CONSTANT TEXT := 'kesplus_jobs_1003';
    
    KESPLUS_JOBS_TASK_NOT_EFFECT_1004 CONSTANT TEXT := 'kesplus_jobs_1004';
     
    KESPLUS_JOBS_CURRENTID_EXISTS_1005 CONSTANT TEXT := 'kesplus_jobs_1005';
     
    KESPLUS_JOBS_TASK_CODE_EXISTS_1006 CONSTANT TEXT := 'kesplus_jobs_1006';
      
    KESPLUS_JOBS_CURRENTID_NOT_EXISTS_1007 CONSTANT TEXT := 'kesplus_jobs_1007';
      
    KESPLUS_JOBS_DIRETORY_NO_DATA_1010 CONSTANT TEXT := 'kesplus_jobs_1010';
      
    KESPLUS_JOBS_SCHEDULED_TASK_NOT_DUPLICATED_1011 CONSTANT TEXT := 'kesplus_jobs_1011';
       
    KESPLUS_JOBS_SCHEDULED_TASK_NAME_REPEAT_1012 CONSTANT TEXT := 'kesplus_jobs_1012';
        
    KESPLUS_JOBS_TASK_NOT_EXISTS_1013 CONSTANT TEXT := 'kesplus_jobs_1013';
    KESPLUS_JOBS_TASK_NULL_CONTENT_1015 CONSTANT TEXT := 'kesplus_jobs_1015';
    
    KESPLUS_LDAP_INPUT_DATA_1001 CONSTANT TEXT := 'kesplus_ldap_1001';
     
    KESPLUS_LDAP_DELETE_DATA_1002 CONSTANT TEXT := 'kesplus_ldap_1002';
     
    KESPLUS_MODULE_NOT_ALLOWED_DELETE_BUILT_IN_MODULES_1001 CONSTANT TEXT := 'kesplus_module_1001';
         
    KESPLUS_MODULE_CODE_EXISTS_2008 CONSTANT TEXT := 'kesplus_module_2008';
    RESTFUL_METHOD_NOT_SUPPORT CONSTANT TEXT := 'kesplus_restful_1007'; 
    RESTFUL_NO_SETTING_AUTH CONSTANT TEXT := 'kesplus_restful_1008'; 
    RESTFUL_NO_EXISTS CONSTANT TEXT := 'kesplus_restful_1009'; 
    SYSTEM_RESTFUL_NOT_DELETE CONSTANT TEXT := 'kesplus_restful_1010'; 
    RESTFUL_ID_IS_NULL CONSTANT TEXT := 'kesplus_restful_1011'; 
    RESTFUL_NAME_IS_NULL CONSTANT TEXT := 'kesplus_restful_1012'; 
    RESTFUL_TREE_ERROR CONSTANT TEXT := 'kesplus_restful_1013'; 
    RESTFUL_VIEW_ID_NO_EXISTS CONSTANT TEXT := 'kesplus_restful_1014'; 
    RESTFUL_FUN_ID_NO_EXISTS CONSTANT TEXT := 'kesplus_restful_1015'; 
    RESTFUL_PERMISSIONID_IS_NULL CONSTANT TEXT := 'kesplus_restful_1016'; 
    RESTFUL_CODE_EXISTS CONSTANT TEXT := 'kesplus_restful_1017'; 
    RESTFUL_PATH_EXISTS CONSTANT TEXT := 'kesplus_restful_1018'; 
    RESTFUL_TITLE_EXISTS CONSTANT TEXT := 'kesplus_restful_1019'; 
    PERMISSION_DATA_NOT_EMPTY CONSTANT TEXT := 'kesplus_perm_1000'; 
    PERMISSION_CODE_EXISTS CONSTANT TEXT := 'kesplus_perm_1001'; 
    PERMISSION_SELECT_DELETE_DATA CONSTANT TEXT := 'kesplus_perm_1002'; 
    PERMISSION_QUERY_NOT_NULL CONSTANT TEXT := 'kesplus_perm_1003'; 
    PERMISSION_DELETE_DIR_ERROR CONSTANT TEXT := 'kesplus_perm_1004'; 
    
    KESPLUS_VIEW_NAME_AND_DIRECTORY_MUST_BE_UNIQUE_1001 CONSTANT TEXT := 'kesplus_view_1001';
    
    KESPLUS_VIEW_SCHEMA_NAME_CANNOT_BE_EMPTY_1002 CONSTANT TEXT := 'kesplus_view_1002';
    
    KESPLUS_VIEW_NAME_ALREADY_EXISTS_1003 CONSTANT TEXT := 'kesplus_view_1003';
    
    KESPLUS_VIEW_ID_CANNOT_BE_EMPTY_1004 CONSTANT TEXT := 'kesplus_view_1004';
    
    KESPLUS_VIEW_INPUT_NEW_NAME_1005 CONSTANT TEXT := 'kesplus_view_1005';
    
    KESPLUS_VIEW_NAME_ALREADY_EXISTS_1006 CONSTANT TEXT := 'kesplus_view_1006';
    
    KESPLUS_VIEW_API_DIRECT_ID_IS_EMPTY_1007 CONSTANT TEXT := 'kesplus_view_1007';
    DIRECTORY_NOT_EXISTS CONSTANT TEXT := 'kesplus_directory_1000'; 
    ROUTE_SERVICE_ALREADY_USED CONSTANT TEXT := 'kesplus_route_1000'; 
     
    KESPLUS_MODULE_ENCODINGCANNOT_CONTAIN_SPECIAL_CHARATERS_1002 CONSTANT TEXT := 'kesplus_module_1022';
    
    KESPLUS_PACKAGES_ID_IS_NULL_1001 CONSTANT TEXT := 'kesplus_packages_1001';
     
    KESPLUS_PACKAGES_CONTENT_IS_NOT_EXISTS_1002 CONSTANT TEXT := 'kesplus_packages_1002';
    
    KESPLUS_PACKAGES_CHECK_THE_SCRIPT_IS_WRITTEN_1003 CONSTANT TEXT := 'kesplus_packages_1003';
    
    KESPLUS_PACKAGES_INOUT_NEW_PACKAGE_NAME_1004 CONSTANT TEXT := 'kesplus_packages_1004';
     
    KESPLUS_ROUTEINFO_THE_SERVICE_HAS_USED_1001 CONSTANT TEXT := 'kesplus_routeinfo_1001';
     
    KESPLUS_SERVERINFO_IP_AND_SERVICEPORT_EXISTS_1001 CONSTANT TEXT := 'kesplus_serverinfo_1001';
     
    KESPLUS_SERVERINFO_CURRETN_SERVER_IS_USED_1002 CONSTANT TEXT := 'kesplus_serverinfo_1002';
    
    KESPLUS_TREE_MENU_TYPE_OBJECT_TYPE_CANNOT_BE_NULL_1001 CONSTANT TEXT := 'kesplus_tree_1001';
    
    KESPLUS_TREE_MISS_PK_1002 CONSTANT TEXT := 'kesplus_tree_1002';
    
    KESPLUS_TREE_DELETE_CHILD_FIRST_1003 CONSTANT TEXT := 'kesplus_tree_1003';
    
    KESPLUS_TREE_DIR_ALREADY_EXISTS_1004 CONSTANT TEXT := 'kesplus_tree_1004';
    
    KESPLUS_TREE_PARAENT_DIR_DOSE_NOT_EXISTS_1005 CONSTANT TEXT := 'kesplus_tree_1005';
    
    KESPLUS_TREE_MAX_LEVEL_7_1006 CONSTANT TEXT := 'kesplus_tree_1006';
    
    KESPLUS_TREE_MISSING_PARENT_ID_1007 CONSTANT TEXT := 'kesplus_tree_1007';
    
    KESPLUS_TREE_MISSING_MODULE_INFO_1008 CONSTANT TEXT := 'kesplus_tree_1008';
    
    KESPLUS_TREE_CANNOT_MOVED_ORIGINAL_1009 CONSTANT TEXT := 'kesplus_tree_1009';
    
    KESPLUS_TREE_NO_PARENT_DIR_1010 CONSTANT TEXT := 'kesplus_tree_1010';
    
    KESPLUS_TREE_ONLY_MOVE_CHILD_DIR_1011 CONSTANT TEXT := 'kesplus_tree_1011';
    
    KESPLUS_TREE_DELETE_LOCK CONSTANT TEXT := 'kesplus_tree_1012';
    SEARCH_TREE_NODE_ERROR CONSTANT TEXT := 'kesplus_tree_1013'; 
    
    KESPLUS_SYSVERSION_ID_HAS_EXISTS_1001 CONSTANT TEXT := 'kesplus_sysversion_1001';
     
    KESPLUS_SYSVERSION_VERSION_HAS_EXISTS_1002 CONSTANT TEXT := 'kesplus_sysversion_1002';
    
    KESPLUS_TABLES_SCHEMANAME_IS_NULL_1011 CONSTANT TEXT := 'kesplus_tables_1011';
     
    KESPLUS_TABLES_TABLENAME_IS_NULL_1012 CONSTANT TEXT := 'kesplus_tables_1012';
    
    KESPLUS_TABLES_POLICYNAME_IS_NULL_1013 CONSTANT TEXT := 'kesplus_tables_1013';
    
    KESPLUS_TABLES_DATABASENAME_IS_NULL_1014 CONSTANT TEXT := 'kesplus_tables_1014';
     
    KESPLUS_TABLES_CONSTRAINTNAME_IS_NULL_1015 CONSTANT TEXT := 'kesplus_tables_1015';
     
    KESPLUS_TABLES_TABLEOID_IS_NULL_1016 CONSTANT TEXT := 'kesplus_tables_1016';
      
    KESPLUS_TABLES_INDEXOID_IS_NULL_1017 CONSTANT TEXT := 'kesplus_tables_1017';
      
    KESPLUS_TABLES_PARTITION_IS_NULL_1018 CONSTANT TEXT := 'kesplus_tables_1018';
     
    KESPLUS_TABLES_NAME_IS_NULL_1019 CONSTANT TEXT := 'kesplus_tables_1019';
      
    KESPLUS_TABLES_TABLESCHEMA_IS_NULL_1020 CONSTANT TEXT := 'kesplus_tables_1020';
       
    KESPLUS_TABLES_TABLENAME_IS_NULL_1021 CONSTANT TEXT := 'kesplus_tables_1021';
     
    KESPLUS_TABLES_INDEXMETHOD_IS_NULL_1022 CONSTANT TEXT := 'kesplus_tables_1022';
     
    KESPLUS_TABLES_DIR_NAME_AND_TABLE_NAME_CANNOT_SAME_1023 CONSTANT TEXT :='kesplus_tables_1023';
    
    KESPLUS_TABLES_NAME_CONDITIONS_1024 CONSTANT TEXT :='kesplus_tables_1024';
     
    KESPLUS_TABLES_NAME_ALREADY_EXISTS_1025 CONSTANT TEXT := 'kesplus_tables_1025';
     
    KESPLUS_TABLES_MISSING_ID_1026 CONSTANT TEXT := 'kesplus_tables_1026';
     
    KESPLUS_TABLES_MISSING_DEPTID_1027 CONSTANT TEXT := 'kesplus_tables_1027';
     
    KESPLUS_TABLES_MISSING_MODULE_CODE_1028 CONSTANT TEXT := 'kesplus_tables_1028';
     
    KESPLUS_TABLES_NAME_ALREADY_EXISTS_1029 CONSTANT TEXT :='kesplus_tables_1029';
    
    KESPLUS_TABLES_TYPE_IS_EMPTY_1030 CONSTANT TEXT :='kesplus_tables_1030';
     
    KESPLUS_GENERATOR_SELECT_PARA_NOT_EMPTY_1031 CONSTANT TEXT := 'kesplus_tables_1031';
     
    KESPLUS_TABLE_GET_INFO_ERROR_1032 CONSTANT TEXT := 'kesplus_tables_1032';
    
    KESPLUS_TABLE_LACKS_PK_1033 CONSTANT TEXT := 'kesplus_tables_1033';
    
    KESPLUS_TABLE_PK_TYPE_INCORRECT_1034 CONSTANT TEXT := 'kesplus_tables_1034';
     
    KESPLUS_GENERATOR_INPUT_DATA_1035 CONSTANT TEXT := 'kesplus_tables_1035';
    
    KESPLUS_GENERATOR_SELECT_DELETE_DATA_1036 CONSTANT TEXT := 'kesplus_tables_1036';
    
    KESPLUS_PACKAGE_DIR_NAME_NO_REPEAT CONSTANT TEXT := 'kesplus_package_1001';
    
    KESPLUS_PACKAGE_NAME_EXISTS CONSTANT TEXT := 'kesplus_package_1002';
    KESPLUS_PACKAGE_ALREADY_INIT CONSTANT TEXT := 'kesplus_package_already_init'; 
    KESPLUS_MENU_ALREADY_INIT CONSTANT TEXT := 'kesplus_menu_already_init'; 
    KESPLUS_ILLEGAL_CHARACTER_INIT CONSTANT TEXT := 'kesplus_illegal_character_init'; 
end;

CREATE OR REPLACE PACKAGE BODY "kesplus_app"."error_code" AS WRAPPED
I/HnejJ4IvYHChEGp8PloA==
END;

