CREATE OR REPLACE PROCEDURE kesplus_platform.grant_user_auth(request INOUT jsonb, response INOUT jsonb) AS WRAPPED
mudv1hydu4Qtko2TdRlMw0kH+UM2VKXXfIj6xln7gchR6TPkblvYmG83gSlS
P8rEk/wRn3ZDGFzQATePinBRsfjjeiD+E9f7D6LNGdYm5Rpjc0w9DI25jJfd
zN0dibQx
END;

