CREATE OR REPLACE PROCEDURE kesplus_platform.revoke_user_auth(request INOUT jsonb, response INOUT jsonb) AS WRAPPED
mudv1hydu4Qtko2TdRlMw0kH+UM2VKXXfIj6xln7gchR6TPkblvYmG83gSlS
P8rEeHY9bqvnwW2LTqZIcu7M6Ou2VfZc1LTOJhiIbkrV1W9PdKDSPvnbAq3e
AkjbX5oU
END;

